on:
  push:
    branches:
      - master
#    tags:
#      - "*"

jobs:
  # clojars:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: jlesquembre/clojars-publish-action@0.3
  #       env:
  #         CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
  #         CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}

  jupyter-kernel:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4

       - name: Prepare java
         uses: actions/setup-java@v4.6.0
         with:
           distribution: 'zulu'
           java-version: '17'

        - name: Install clojure tools
          uses: DeLaGuardo/setup-clojure@13.1
          with:
            cli: 1.12.0.1495

        - name: create clojupyter kernel
          run: clojure -T:build create-clojupyter-kernel

             
        - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar    